### ISSUE TITLE
Option to replace default nav to camel nav

### ISSUE THREAD

**Issue by Noitidart** [mlewand/vscode-select-part-of-word#26]
May you please add option to instead of adding new navigation keybindings of `alt+` may you please replace the existing `ctrl+` navigation keybindings.

Because this extension is adding `Ctrl + Alt + Right/Left` but this binding already exists for moving editor into next/prev group (which I use a bit)

**Comment by mlewand** [comment]
@Noitidart let me ensure that I got it right - you're asking to change the default hotkeys, from `Ctrl + Alt + Right/Left` to something like `Ctrl + Right/Left`, correct?

From my perspective `ctl + alt + arrow` seems to be a sweet spot, as personally I'd always like to to keep VSCode's default `ctrl + arrow` hotkey, so that I can move quicker and then as soon as I'm in interesting camelCase word I continue navigation with `ctrl + alt + arrow` to iterate over camelCase part.

Anyway, since you'd basically like to customize the hotkey, have you thought simply about overriding the hotkeys to your like?

Consider `keybindings.json` sth like this:

```json
// (...)
{
        "key": "ctrl+right",
        "command": "selectPartOfWord.moveRight"
    },
    {
        "key": "ctrl+shift+right",
        "command": "selectPartOfWord.selectRight"
    },
```

**Comment by Noitidart** [comment]
Yes sir thats correct. Thanks for that customization idea! Ill try that!

Yep your thoughts makes sense, it's the way Atom does it. I saw Camel had 1k downloads so thought it was a smart move, maybe not. Thanks for the discussion! :)

**Comment by Noitidart** [comment]
Oh wow that was easy, VSCode is awesome!

I modified it like this:

```
    { "key": "ctrl+right",        "command": "selectPartOfWord.moveRight" },
    { "key": "ctrl+left",         "command": "selectPartOfWord.moveLeft" },
    { "key": "ctrl+shift+right",  "command": "selectPartOfWord.selectRight" },
    { "key": "ctrl+shift+left",   "command": "selectPartOfWord.selectLeft" },
    { "key": "ctrl+backspace",    "command": "selectPartOfWord.backspace" },
    { "key": "ctrl+delete", "command": "selectPartOfWord.delete" }
```

Super sweet! Thanks!

**Comment by Noitidart** [comment]
Ah I had to override the default extension keys but pasting again into user defined the defaults. So I had to paste:

```
    { "key": "ctrl+alt+right",        "command": "workbench.action.moveEditorToNextGroup" },
    { "key": "ctrl+alt+left",         "command": "workbench.action.moveEditorToPreviousGroup" }
    { "key": "ctrl+shift+alt+right",  "command": "cursorColumnSelectRight", "when": "editorTextFocus" },
    { "key": "ctrl+shift+alt+left",   "command": "cursorColumnSelectLeft", "when": "editorTextFocus" },
```
 as well.

**Comment by mlewand** [comment]
All right, glad that it worked out fine! It shows that it would be nice to document it somehow in README.md for others. I'll extract it into a separate issue.
