### ISSUE TITLE
Add support of the "Select word" feature (Ctrl+W)

### ISSUE THREAD

**Issue by nZeus** [mlewand/vscode-select-part-of-word#28]
Many IDEs allow to select a word by pressing a CTRL+W.
Unfortunately, VSCode doesn't have it (or I couldn't find it)..
I think this plugin is a good place to have this functionality

**Comment by mlewand** [comment]
@nZeus what is the expected behavior?

Let's assume that `^` denotes collapsed selection (caret). And `[`, `]` are boundaries of ranged selection.

1. You have editor with the following content: `foo myCamelCa^seIdentifier bar`.
1. You press `ctrl/cmd+w`.

What is the expected output? I guess simply `foo [myCamelCaseIdentifier] bar`, right?

That should be implemented as a separate extension though, as this behavior is not really related to camelCasing. However I'm surprised not to see any extension for that function on a Marketplace.

**Comment by nZeus** [comment]
Yes, I would expect to have the following behavior: 

`foo myCamelCa^seIdentifier bar`
ctrl+w -> `foo [myCamelCaseIdentifier] bar`
ctrl+w -> `[foo myCamelCaseIdentifier bar]`

I wasn't sure if this can be done in this plugin, but the name of the plugin "Select part of a word" is very close to the name of this feature :)

Unfortunately, I couldn't find any extension that would do what I want :(

**Comment by mlewand** [comment]
Yea, this feature should get a separate plugin.

I've been thinking about this kind of a feature some time ago, however it was never as crucial for me to roll out an extension for that. Given that there are 2 of us it makes more sense to make it 😉

I'll close this issue, as it's beyond scope of this project. I'll update this issue though if I happen to create an extension like that.

If you need it badly, I suggest you giving a try with it. You can even take this plugin as an template. The best thing is that this plugin has a nice unit tests setup, so you'd have it figured out (which is a bit PITA 😉).
